// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate deploy/dev/status/resolve/diff) needs a direct or session-mode
    // connection, not the transaction pooler used at runtime. DATABASE_URL is only a
    // fallback so `prisma generate` still works where DIRECT_URL is not set (e.g. the Vercel build).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
